### ISSUE TITLE
Failing to install for Ruby <= 2.1 since 1.4.0

### ISSUE THREAD

**Issue by marcotc** [msgpack/msgpack-ruby#205]
I tried installing the last release of `msgpack` on Ruby 2.1, but got a compilation error:
```
$ ruby -v
ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-darwin18.0]
$ gem install msgpack -v 1.4.0
Fetching: msgpack-1.4.0.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing msgpack:
        ERROR: Failed to build gem native extension.

    /Users/marco.costa/.rbenv/versions/2.1.10/bin/ruby extconf.rb
checking for ruby/st.h... yes
checking for st.h... yes
checking for rb_str_replace() in ruby.h... yes
checking for rb_intern_str() in ruby.h... yes
checking for rb_enc_interned_str() in ruby.h... no
checking for rb_sym2str() in ruby.h... no
checking for rb_str_intern() in ruby.h... yes
checking for rb_block_lambda() in ruby.h... yes
checking for rb_hash_dup() in ruby.h... yes
checking for rb_hash_clear() in ruby.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling unpacker_class.c
In file included from unpacker_class.c:19:
In file included from ./unpacker.h:21:
./buffer.h:472:18: error: implicit declaration of function 'rb_utf8_str_new' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        result = rb_utf8_str_new(b->read_buffer, length);
                 ^
./buffer.h:472:18: note: did you mean 'rb_enc_str_new'?
/Users/marco.costa/.rbenv/versions/2.1.10/include/ruby-2.1.0/ruby/encoding.h:91:7: note: 'rb_enc_str_new' declared here
VALUE rb_enc_str_new(const char*, long, rb_encoding*);
      ^
1 error generated.
make: *** [unpacker_class.o] Error 1

make failed, exit code 2
```

I believe this was introduced in https://github.com/msgpack/msgpack-ruby/pull/196.

**Comment by tagomoris** [comment]
Ruby 2.1's EoL (End of Life) was April 1, 2017, and the latest msgpack-ruby doesn't support that version now.
It is an intentional change.

**Comment by HoneyryderChuck** [comment]
Had the same error.

@tagomoris if that is so, then it should be properly advertised, both in the CHANGELOG, as well as in the required ruby version constraint from the gemspec. Compiling-then-failing at runtime is not the greatest of experiences.

**Comment by tagomoris** [comment]
I still STRONGLY recommend to stop using EoL Ruby versions, but it's also reasonable to restrict using recent msgpack versions on such old rubies.
I'll release 1.4.2 with required-ruby-version, then yank 1.4.0 and 1.4.1 from RubyGems.org.

**Comment by tagomoris** [comment]
I've released v1.4.2 with `required_ruby_version >= 2.4` and yanked 1.4.0 and 1.4.1.
@marcotc @HoneyryderChuck Could you confirm it in your environment?

**Comment by regentgal** [comment]
Yanking 1.4.1 has broken our bundle 

```
? bundle                                                               
Fetching gem metadata from https://rubygems.org/........
Your bundle is locked to msgpack (1.4.1), but that version could not be found in any of the sources listed in your
Gemfile. If you haven't changed sources, that means the author of msgpack (1.4.1) has removed it. You'll need to
update your bundle to a version other than msgpack (1.4.1) that hasn't been removed in order to install.
? ruby --version                                                         7 ↵
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
```

We are indirectly dependent on msgpack through bootsnap

```
 bootsnap (1.6.0)
      msgpack (~> 1.0)
```

**Comment by ro-savage** [comment]
@tagomoris - Yanking the versions broke our builds as well. (We had to manually upgrade msgpack in our ruby-lock)

**Comment by tagomoris** [comment]
I'm very sorry for the case that `Gemfile.lock` already specifies `1.4.1` (or `1.4.0`), but yanking those versions is the only solution for this problem. Please update it again to `1.4.2`.
Thank you for trying those versions very early, and reporting your situation.

**Comment by ro-savage** [comment]
Thanks for rectifying it so quickly and being so responsive. You're a great maintainer! 

FYI, we use Github Dependabot which updated gem that asked with a dependency of `msgpack (~> 1.0)`.

When the gem (bootsnap) was updated it automatically updated our lockfile to the latest msgpack at the time.

I am not sure how things are done in the ruby world, but on NPM they don't allow pulling a released version, you must just release a new version. To avoid the issue where someone's build breaks because a deep dependency is pulled from the package manager. (Implemented after [left-pad was pulled](https://thenewstack.io/the-kik-kerfuffle/) by maintainer and broke thousands of builds)

**Comment by HoneyryderChuck** [comment]
@tagomoris I saw you took action, thank you for this.

Just a heads-up that 1.4.0 was working fine in ruby 2.2 . I'll take from the comments above that setting minimal supported ruby to 2.4 has to do with following the EOLs from the ruby core team.

As much as I can relate to the limitations of supporting older rubies, I'm also not in favour of adopting the ruby core team support policy for no apparent reason. As people already pointed out,  `bootsnap` depends on `msgpack`, and rails 5.2 depends on `bootsnap`. 5.2's minimal ruby version is 2.2 . So this change can have the unfortunate side-effect of causing significant builds to break (ruby  2.3 is after all, the most widely deployed ruby version according to the latest surveys), and this might escalate back to your inbox, thereby increasing your support overhead. Wouldn't setting the minimal version to 2.2 have been good enough, considering that it still works?

Do consider that, hadn't it worked, my opinion on the matter would have been different. Also, you're the maintainer, so it's your call, regardless of my opinion.

**Comment by marcotc** [comment]
Thank you for the super responsive actions, @tagomoris.

For my original use case, the issue is no longer present and I'm ok with closing this GH issue.

Yanking the "bad" versions from RubyGems now allow bundler to correctly install the latest working version for Ruby 2.0 and 2.1 (`1.3.3`).

**Comment by tagomoris** [comment]
@HoneyryderChuck If you (and other people) want to keep using old versions even after EoLs, you can lock the dependency explicitly. Ruby 2.2 was outdated years ago, and even security fixes will not be provided for that version. Keeping C API interoperability for such versions decreases maintainability so much.
Thanks for your opinion.

**Comment by zahiar** [comment]
For such a breaking change, any reason why this package wasn't bumped to 2.0.0 (next major version), that way this wouldn't have broken so much stuff that brings in msgpack loosely, aka any 1.x.x version rather than an explicit pinned version.
