### PR TITLE
use a new loading mechanism on jruby

### PR DESCRIPTION
**Pull request by ahorek**
this PR fixes https://github.com/msgpack/msgpack-ruby/issues/226 compatibility for JRuby 9.3.x
and drops support for JRuby 9.1.x. Since the [minimum supported Ruby version](https://github.com/msgpack/msgpack-ruby/blob/master/msgpack.gemspec#L23) is 2.4 and JRuby 9.1.x targets 2.3 I guess it's ok.

see also https://github.com/jruby/jruby/issues/6868

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
Hello, @ahorek Thank you for creating this PR. 
This PR better than my change(#227). correct?
If so, I'll close my PR. 

Thank you.

**Comment by ahorek** [comment]
yes, thanks for letting us know about the problem. Your change is an option, but the new syntax is preferred, since we don't need compatibility with EOL versions of JRuby.

**Comment by hiroyuki-sato** [comment]
Thank you for your comment. #227 closed.

**Comment by tagomoris** [comment]
Thanks for creating the change!
CI is failing, but it's fixed at #230 
```
  1) MessagePack::Unpacker ensure string hash keys are deduplicated
     Failure/Error: expect(hashes[0].keys.first).to equal(hashes[1].keys.first)

       expected #<String:4020> => "foo"
            got #<String:4024> => "foo"

       Compared using equal?, which compares object identity,
       but expected and actual are not the same object. Use
       `expect(actual).to eq(expected)` if you don't care about
       object identity in this example.
     # ./spec/unpacker_spec.rb:37:in `block in <main>'
```

**Comment by ivoanjo** [comment]
While testing #239 I ran into an issue: the new loading mechanism only works from JRuby 9.2.1.0+ on, aka it doesn't work on the 9.2.0.0 release.

I don't think it's worth fixing it; just thought I drop here a note in case someone runs into 
``NoMethodError: undefined method `load_ext' for JRuby::Util:Module`` on msgpack 1.4.4+ on JRuby 9.2.0.0, which hopefully is absolutely nobody.
